# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack_fmi', '0007_team_mentors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='place',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
