# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack_fmi', '0008_auto_20161114_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='picture',
        ),
    ]
