# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hack_fmi', '0011_blacklisttoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonCompetitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_for_team', models.BooleanField(default=False)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hack_fmi.Competitor')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hack_fmi.Season')),
            ],
        ),
    ]
