# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 10:37
from __future__ import unicode_literals

from django.db import migrations


def create_season_competitor_infos_for_current_season(apps, schema_editor):
    Competitor = apps.get_model('hack_fmi', 'Competitor')
    Season = apps.get_model('hack_fmi', 'Season')
    SeasonCompetitorInfo = apps.get_model('hack_fmi', 'SeasonCompetitorInfo')

    competitors_without_sci = Competitor.objects.filter(seasoncompetitorinfo__isnull=True)
    try:
        active_season = Season.objects.get(is_active=True)
        season_competitor_infos = []

        for competitor in competitors_without_sci:
            season_competitor_infos.append(SeasonCompetitorInfo(competitor=competitor,
                                                                season=active_season))

        SeasonCompetitorInfo.objects.bulk_create(season_competitor_infos)
    except Season.DoesNotExist:
        """
        There is no active season at the moment.
        """


class Migration(migrations.Migration):

    dependencies = [
        ('hack_fmi', '0013_auto_20161128_1841'),
    ]

    operations = [
        migrations.RunPython(create_season_competitor_infos_for_current_season),
    ]
