# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack_fmi', '0014_data_migration_create_season_competitor_infos_for_the_current_active_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='updated_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
