# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hack_fmi', '0015_team_updated_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammentorship',
            unique_together=set([('mentor', 'team')]),
        ),
    ]
