language: python
python:
- '3.4'
addons:
  postgresql: '9.3'
services: postgresql
install:
- pip install -r requirements/base.txt
- pip install -r requirements/test.txt 
before_script:
- psql -c 'CREATE DATABASE loki;' -U postgres
- psql -c 'CREATE DATABASE testdb;' -U postgres
script:
- export DJANGO_SETTINGS_MODULE=config.settings.tests
- python manage.py migrate
- flake8
- coverage run --source='.' -m py.test
after_success:
- coveralls --rcfile=.coverage.rc
notifications:
  slack:
    secure: UJWWLC1NEy5slof7PrsrpGjL0ydS7jHBkeog6owqSk6avgOlbE7xGvKNiLfawJOIJ9SkOzaKJIxnCZ37QutT70gtwnb/a+cLK1XhNXuAiRE9OKIFCRSsMX3FxEX0YHIeHE1Q4EoMOr7pCWAFCGRReZNhAHvpRkfzO0F1KBtbCLI=
    on_success: change
    on_failure: change
