language : python
python:
  - '3.4'

addons:
  postgresql: '9.3'

services : postgresql

install:
  - pip install -r requirements.txt --use-mirrors

before_script:
  - psql -c 'CREATE DATABASE testdb;' -U postgres

script:
  - python loki/manage.py migrate
  - coverage run --source='.' loki/manage.py test

after_success:
  - coveralls --rcfile=.coverage.rc
