# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
