# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0002_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='courses_to_interview',
            field=models.ManyToManyField(to='applications.ApplicationInfo'),
        ),
    ]
