# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0003_auto_20160911_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interviewer_time_slot',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='interview_system.InterviewerFreeTime'),
        ),
        migrations.AddField(
            model_name='interviewerfreetime',
            name='buffer_time',
            field=models.BooleanField(default=False),
        ),
    ]
