# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0004_auto_20160915_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='buffer_time',
            field=models.BooleanField(default=False),
        ),
    ]
