# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0005_interview_buffer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.Application'),
        ),
    ]
