# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0008_auto_20160924_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
