# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20160923_1314'),
        ('interview_system', '0010_interviewer_skype'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='app_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.ApplicationInfo'),
        ),
    ]
