# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import education.validators


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_auto_20160809_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='mac',
            field=models.CharField(max_length=17, null=True, validators=[education.validators.validate_mac]),
        ),
    ]
