# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_auto_20160718_1714'),
        ('education', '0012_auto_20160810_1532'),
    ]

    operations = [
    ]
