# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_courseapplytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tasks_for_apply',
            field=models.ManyToManyField(to='education.CourseApplyTask'),
        ),
    ]
