# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_course_tasks_for_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseapplytask',
            name='apply_for_courses',
        ),
    ]
