# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_auto_20160901_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='SEO_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='SEO_title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='show_on_index',
        ),
        migrations.RemoveField(
            model_name='course',
            name='url',
        ),
    ]
