# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_remove_courseapplytask_apply_for_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tasks_for_apply',
        ),
        migrations.DeleteModel(
            name='CourseApplyTask',
        ),
    ]
