# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_auto_20160901_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
