# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_merge'),
        ('education', '0016_auto_20160820_1045'),
    ]

    operations = [
    ]
