# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 11:57
from __future__ import unicode_literals

from django.db import migrations

def migrate_video(apps, schema_editor):
    Course = apps.get_model('education', 'Course')
    CourseDescription = apps.get_model('website', 'CourseDescription')

    for course in Course.objects.all():
        cd = CourseDescription.objects.filter(course=course)

        if cd.exists():
            cd = cd.last()
            cd.video = course.video
            cd.save()


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_auto_20160901_1447'),
    ]

    operations = [
        migrations.RunPython(migrate_video)
    ]
