# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 11:57
from __future__ import unicode_literals

from django.db import migrations
from loki.education.models import Course
from loki.website.models import CourseDescription

def migrate_video(apps, schema_editor):
    for course in Course.objects.all():
        cd = CourseDescription.objects.filter(course=course)

        if cd.exists():
            cd = cd.last()
            cd.video = course.video
            cd.save()


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_auto_20160901_1447'),
    ]

    operations = [
        migrations.RunPython(migrate_video)
    ]
