# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_data_migrate_video_from_course_to_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
    ]
