# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_merge'),
        ('education', '0019_remove_course_video'),
    ]

    operations = [
    ]
