# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
    ]
