# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_remove_course_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='application_until',
        ),
        migrations.RemoveField(
            model_name='course',
            name='applications_url',
        ),
    ]
