# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_auto_20160906_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_channel',
            field=models.URLField(blank=True, null=True),
        ),
    ]
