# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import loki.education.validators


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0023_course_video_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[loki.education.validators.validate_mac]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[loki.education.validators.validate_mac]),
        ),
    ]
