# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0027_lecture_presentation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
