# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 14:05
from __future__ import unicode_literals

from django.db import migrations


def migrate_student_to_baseuser(apps, schema_editor):
    CheckIn = apps.get_model("education", "CheckIn")
    Teacher = apps.get_model("education", "Teacher")
    BaseUser = apps.get_model("base_app", "BaseUser")
    for checkin in CheckIn.objects.all():
        if checkin.student:
            checkin.user = BaseUser.objects.get(id=checkin.student.baseuser_ptr_id)
        else:
            try:
                teacher = Teacher.objects.get(mac=checkin.mac)
                checkin.user = BaseUser.objects.get(id=teacher.baseuser_ptr_id)
            except Teacher.MultipleObjectsReturned:
                print(checkin.mac)
            except Teacher.DoesNotExist:
                """
                Only Student and Teacher can have mac address. If mac address
                does not match both teacher and student mac addresses, checkin
                user shall stay empty.
                """
                pass
        checkin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0029_checkin_user'),
    ]

    operations = [
        migrations.RunPython(migrate_student_to_baseuser),
    ]
