# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0030_data_migration_migrate_student_to_user_in_checkin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='student',
        ),
    ]
