# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0032_auto_20161115_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='teacher_comment',
            field=models.TextField(blank=True, help_text='Коментар от интервюиращия', null=True),
        ),
    ]
