# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0033_student_looking_for_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingat',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.City'),
        ),
    ]
