# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0033_courseassignment_teacher_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseassignment',
            name='teacher_comment',
        ),
    ]
