# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0034_auto_20170127_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
