# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-14 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0035_course_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='english_names',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
