# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-20 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0036_course_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='percent_submitted_solutions',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
