# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-31 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0037_courseassignment_percent_submitted_solutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassignment',
            name='percent_submitted_solutions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
