# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_app', '0016_auto_20160816_2208'),
        ('education', '0015_remove_courseapplytask_apply_for_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyCourse',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('skype', models.CharField(blank=True, max_length=30, null=True)),
                ('works_at', models.CharField(blank=True, max_length=110, null=True)),
                ('studies_at', models.CharField(blank=True, max_length=110, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='education.Course')),
            ],
        ),
    ]
