# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
    ]
