# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationinfo_external_application_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationproblemsolution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.ApplicationProblem'),
        ),
    ]
