# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20160820_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.ApplicationInfo'),
        ),
        migrations.AlterField(
            model_name='applicationproblemsolution',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.ApplicationProblem'),
        ),
    ]
