# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 11:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20160905_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinfo',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Това описва процедурата по кандидатстване. Излиза тук /apply/edit/<course-url>', null=True),
        ),
    ]
