# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20160902_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationproblem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
