# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicationinfo_description'),
        ('applications', '0003_auto_20160901_1820'),
    ]

    operations = [
    ]
