# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_interview_date',
            field=models.BooleanField(default=False),
        ),
    ]
