# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_has_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinfo',
            name='end_interview_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='applicationinfo',
            name='start_interview_date',
            field=models.DateTimeField(null=True),
        ),
    ]
