# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 16:40
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_baseuser_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='full_image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=''),
        ),
    ]
