# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-14 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_auto_20160816_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='english_names',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
