# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0017_auto_20160802_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='full_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
