# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0017_baseuser_english_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
