# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0018_auto_20160802_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='cropping_free',
            field=image_cropping.fields.ImageRatioField('full_image', '300x230', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping free'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('full_image', '430x360', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='full_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
