# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 19:27
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0020_auto_20160803_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='full_image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='/home/rositsazz/Loki/Loki/loki/media/avatars/'),
        ),
    ]
