# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 20:12
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0023_auto_20160803_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('full_image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
