# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 21:55
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0025_auto_20160803_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='avatar',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=''),
        ),
    ]
