# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_coursedescription_list_courses_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedescription',
            old_name='price',
            new_name='price_text',
        ),
    ]
