# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160907_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedescription',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
